### ISSUE TITLE
[Quest] Bloody Breakout

### ISSUE THREAD

**Issue by ShokzDev** [AshamaneProject/AshamaneCore#725]
**Description:**
- High Inquisitor Valroth does not despoil his head 

**Usefull Wowhead links:**
http://www.wowhead.com/quest=12727/bloody-breakout
http://www.wowhead.com/item=39510/valroths-head#objective-of
http://www.wowhead.com/npc=29001/high-inquisitor-valroth

**Comment by Neredun** [comment]
http://www.wowhead.com/object=191092 You should loot the head from this Object.

**Comment by Neredun** [comment]
i think it would be worth mention that Koltira Deathweaver starts his Waypoint at the first spawn of the Crimson Acolytes. But he should start his waypoint AFTER the dead of Valroth (who rarely spawns)

**Comment by Neredun** [comment]
![wowscrnshot_040218_125844](https://user-images.githubusercontent.com/21986277/38203465-b09e67d6-3675-11e8-95c0-8ba4950bc95f.jpg)

High Inquisitor Valroth's is nowhere to found. And you can see his body despawning here

**Comment by HannibalRoG** [comment]
Fixed in https://github.com/AshamaneProject/AshamaneCore/commit/c4cccc5e6a298c3ce0d68d0c520ea5b328f23f1a

**Comment by Neredun** [comment]
Tested it yesterday. Quest still have problems and can't be completed... Koltira still stars his waypoints Very Early and Valroth Remains never spawns.
